language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash amber/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - phpunit -c amber/phpunit.xml
  - phpunit --exclude-group ExternalInterfaces amber/libraries
